const commonStyles = `
.text {
  font-size: 14px;
  color: #666;
}

.small-text {
  font-size: 11px;
  color: #666;
}

.logo {
  width: 300px
}

body {
  display: grid;
  justify-items: center;
  align-items: center;
  height: 100vh;
  margin: 0;
}

hr {
  width: 100%;
  margin-top: 20px;
  margin-bottom: 20px
}

.container {
  width: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
  height: 100vh;
}

.sub-container {
  width: fit-content;
  text-align: center;
  padding: 20px;
  border: 1px solid #ccc;
  border-radius: 10px;
  box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
}
`

export const sendResetPasswordEmailCss = `<style>
.title {
  font-size: 24px;
  color: #F75D5F;
  font-weight: bold;
  margin-bottom: 20px;
  margin-top: 20px
}

${commonStyles}

</style>`

export const sendEmailToLocaleCss = `<style>
.title {
  font-size: 16px;
  color: #F75D5F;
  font-weight: bold;
  margin-bottom: 20px;
  margin-top: 20px
}

${commonStyles}
</style>`

export const sendAutoGeneratedPasswordEmailCss = `<style>
.title {
  font-size: 16px;
  color: #F75D5F;
  font-weight: bold;
  margin-bottom: 20px;
  margin-top: 20px
}

${commonStyles}

</style>`

export const sendEmailVerificationCodeCss = `<style>
.title {
  font-size: 24px;
  color: #F75D5F;
  font-weight: bold;
  margin-bottom: 20px;
  margin-top: 20px
}

${commonStyles}

</style>`
